easy_admin:
    formats:
        date:     'd/m/Y'           # Format d'affichage des dates
        time:     'H:i:s'           # Format d'affichage des heures/minutes/secondes
        datetime: 'd/m/Y H:i:s'     # Format d'affichage des datetime
    site_name: 'Administration Générale'    # Nom du backoffice, marqué en haut à gauche de l'interface
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"           # Active le thème de bootstrap 4 pour l'apparence des formulaires
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"     # Active le thème de ckeditor pour les champs ckeditor
        brand_color: 'black'        # Couleur principale du backoffice (boutons, icônes, etc...)
        menu:       # Paramétrage du menu de gauche
            - { label: 'Revenir au site', route: 'main_home', icon: 'link'}     # Création d'un lien permettant de revenir sur le site sur l'accueil
            - User      # Affiche le menu principal pour l'entité "User" (on pourrait en mettre d'autres pour d'autres entités du site)
    entities:       # Paramétrage de la gestion des entités du site par easyadmin
        User:       # Paramétrage de l'entité User
            class: App\Entity\User      # Classe de l'entité User
            label: 'Utilisateurs'       # Nom d'affichage de l'entité User
            list:       # Paramétrage de l'onglet d'affichage des utilisateurs
                title: 'Liste des utilisateurs'     # Titre de l'onglet
                sort: ['id', 'ASC']     # Tri par défaut
                fields:     # Paramétrage des colonnes affichées ainsi que de leur type et leur titre
                    - {property: 'id', label: 'ID'}
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'pseudonym', label: 'Pseudonyme'}
                    - {property: 'activated', label: 'Email confirmé'}
                    - {property: 'registrationDate', label: 'Date d''inscription'}  # '' permet d'échapper
            edit:   # Paramétrage de l'onglet de modification d'un utilisateur
                title: 'Modifier un utilisateur'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire d'édition, ainsi que leur type et leur label
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'pseudonym', label: 'Pseudonyme'}
                    - {property: 'activated', label: 'Email confirmé'}
                    - {property: 'registrationDate', label: 'Date d''inscription'}
                    - {property: 'activationToken', label: 'Token d''activation'}
            new:    # Paramétrage de l'onglet d'ajout d'un utilisateur
                title: 'Créer un nouveau compte'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire de création, ainsi que leur type et leur label
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'password', type: 'password', label: 'Mot de passe'}
                    - {property: 'pseudonym', label: 'Pseudonyme'}
                    - {property: 'activated', label: 'Email confirmé'}
                    - {property: 'registrationDate', label: 'Date d''inscription'}
                    - {property: 'activationToken', label: 'Token d''activation'}